const { Schema, default: mongoose } = require("mongoose");

const orderSchema = new Schema ({
    _id: Schema.Types.ObjectId,
    cart_item: [{
        product: Schema.Types.ObjectId,
        variantId: Schema.Types.ObjectId,
        series: String,
        item_count: Number, //to do: restrict to integers
        quantity: Number, //to do: restrict to integers
        cogs: Number,
        price: Number,  
        series: String,
        vendorMargin: Number,
        orderStatus: String
    }],
    paymentAt: Schema.Types.Date
})

const Order = mongoose.model('Order', orderSchema)

// in a database export _id's are given and they cannot be autogenerated again since the relations would be lost. 
// this method assumes orderData already has an _id component 
exports.createOrderFromExport = function(orderData) {
    const newOrder = new Order(orderData)
    return newOrder.save()
}